POST http://localhost:3001/todos HTTP/1.1
content-type: application/json

{
    "name": "Seguaandaaaa atodo"
}

###
GET http://localhost:3001/todos HTTP/1.1
###
GET http://localhost:3001/todos/1 HTTP/1.1
###
PATCH  http://localhost:3001/todos/1 HTTP/1.1
content-type: application/json

{
    "name": "primeiaraoaaa todo alterado"
}

###
POST http://localhost:3001/task HTTP/1.1
content-type: application/json

{
  "name": "TERCEIRA task para linkar com o primeiro todo",
  "completed": false,
  "todoId": 1
}

###
GET http://localhost:3001/task HTTP/1.1

###
PATCH  http://localhost:3001/task/1/3 HTTP/1.1
content-type: application/json

{
    "completed": true
}

###
DELETE  http://localhost:3001/task/1/2 HTTP/1.1
###
DELETE  http://localhost:3001/todos/7 HTTP/1.1
